### PANDAS

Pandas - сокращение от panel data (табличные данные). Это библиотека, которая используется в основном для анализа данных и машинного обучения, но в ней также удобно, например, обрабатывать выдачу из корпуса типа ГИКРЯ и любые другие текстовые данные, которые содержатся в табличках.

Pandas - очень быстрая библиотека, потому что основывается на библиотеке numpy, а та, как мы помним, написана внутри себя на языке С. С этим фактом связаны и типы данных pandas - они во многом дублируют типы numpy, пришедшие из С.

Pandas **гораздо** быстрее обрабатывает данные, чем стандартные методы питона, в частности циклы. Старайтесь не использовать циклы в pandas, как и в numpy.

Библиотеку необходимо сперва установить:

    pip install pandas

Затем ее, конечно, нужно импортировать. Как и для numpy, для pandas существует устоявшееся сокращение.

In [ ]:
import pandas as pd

#### Понятия DataFrame и Series, создание таблиц

Два основных класса, которые есть в модуле - это класс DataFrame (собственно таблица) и класс Series (колонка или строка в таблице). Создать DataFrame можно из списка списков, списка словарей, словаря списков или словаря словарей.

Приятная фишка pandas в том, что он заточен под использование в тетрадках .ipynb и умеет красиво отображать данные. Но для этого надо работать в консольном режиме, то есть обращаться к самим объектам pandas, а не к результату их обработки стандартными функциями питона. Сравните то, что выдает pandas, с результатом print().

In [ ]:
df1 = pd.DataFrame([[1, 2, 3], [4, 5, 6]])
print("Это стандартный print:\n")
print(df1)
print("\nА это собственно pandas:\n")
df1

Это стандартный print:

   0  1  2
0  1  2  3
1  4  5  6

А это собственно pandas:

   0  1  2
0  1  2  3
1  4  5  6

Когда мы создаем DataFrame из списка словарей, то указываем в ключах имена столбцов. Так же поступаем в случае словаря списков.

In [ ]:
df2 = pd.DataFrame([{'col1': 1, 'col2': 2}, {'col1': 3, 'col2': 4}])
df2

   col1  col2
0     1     2
1     3     4

In [ ]:
df3 = pd.DataFrame({'col1': [1, 2, 3], 'col2': [4, 5, 6]})
df3

   col1  col2
0     1     4
1     2     5
2     3     6

В случае словаря словарей вторыми (внутренними) ключами будут имена строк.

In [ ]:
df4 = pd.DataFrame({'col1': {'l1': 1, 'l2': 2}, 'col2': {'l1': 3, 'l2': 4}})
df4

    col1  col2
l1     1     3
l2     2     4

Также pandas отлично работает с csv, json, excel-файлами. Для excel, правда, нужно дополнительно установить openpyxl. Интерфейс очень простой: достаточно написать функцию для чтения этого формата и передать только путь к файлу.

    data = pd.read_json(path)
    data = pd.read_csv(path)
    data = pd.read_excel(path)

#### Индексация, просмотр, фильтрация

Внутри себя табличка pandas устроена очень похоже именно на помесь словаря и списка, поэтому можно обращаться к ее частям, как к ключам в словаре или индексам в списке:

In [ ]:
df3['col1']

0    1
1    2
2    3
Name: col1, dtype: int64

Когда мы так делаем, нам показывается формат Series - та самая колонка (или строчка) таблицы. Помимо имени колонки (или индекса строки), pandas еще указывает тип данных, которые содержатся в ячейках. Поскольку pandas основан на numpy, pandas тоже указывает немного непривычные int64, float32 и подобное.

К колонке таблицы, можно обращаться через точку от имени таблицы:

In [ ]:
df3.col1

0    1
1    2
2    3
Name: col1, dtype: int64

Правда, этот способ работает, только если в ее имени нет каких-нибудь пробелов и нестандартных символов. Если они есть, пишем квадратные скобки. Так же лучше поступать, если названия столбцов у вас не на латинице (хотя современный pandas вполне позволяет, например, кириллическое название столбца написать через точку).

In [ ]:
df5 = pd.DataFrame({'столбец 1': [1, 2], 'столбец 2': [3, 4]})
df5['столбец 1']

0    1
1    2
Name: столбец 1, dtype: int64

Строки мы смотрим с помощью loc. Обратите внимание, что строка выведется все равно в сертикальном направлении:

In [ ]:
df4.loc['l2']

col1    2
col2    4
Name: l2, dtype: int64

Если у нас вместо индексов у строчек названия, то пишем прямо названия, как в ячейке выше. Если индексы - числа, то можно писать числа. Можно вообще всегда писать числа, если использовать iloc:

In [ ]:
df4.iloc[1]

col1    2
col2    4
Name: l2, dtype: int64

Кстати, у любой таблички pandas можно посмотреть количество ее строк с помощью самой обычной функции len().

К отдельной ячейке можно обратиться, если сперва указать ее колонку, а потом строку:

In [ ]:
df4['col2']['l1']

3

Также можно воспользоваться iloc:

In [ ]:
df4.iloc[0, 1]  # 0 - номер колонки, 1 - номер строки

3

Общее количество элементов таблицы (включая NaN и пустые ячейки, если они есть) можно посмотреть с помощью .size.

In [ ]:
df4.size

4

Наконец, pandas умеет показывать отдельно начало, отдельно конец таблицы и выбирать случайные строки для показа.

Здесь для демонстрации используется обычная тренировочная база данных по пассажирам "Титаника". Она сохранена у вас в файле под именем 'train.csv'. Не забудьте добавить ее в папку, прежде чем запускать ячейку ниже!

In [ ]:
titanic = pd.read_csv('train.csv')
titanic.head() # по умолчанию показывает первые 5 строк; можно в скобочках указать другое число

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
titanic.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [ ]:
titanic.sample(3)  # по умолчанию показывает одну случайную строку

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
417,418,1,2,"Silven, Miss. Lyyli Karoliina",female,18.0,0,2,250652,13.000,NaN,S
104,105,0,3,"Gustafsson, Mr. Anders Vilhelm",male,37.0,2,0,3101276,7.925,NaN,S
45,46,0,3,"Rogers, Mr. William John",male,NaN,0,0,S.C./A.4. 23567,8.050,NaN,S

Также можно посмотреть отдельно индексы и отдельно список имен колонок для таблицы:

In [ ]:
titanic.index

RangeIndex(start=0, stop=891, step=1)

In [ ]:
df4.index

Index(['l1', 'l2'], dtype='object')

In [ ]:
titanic.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

Можно сразу попросить pandas описать загруженную табличку, а то еще и немного проанализировать ее за нас:

In [ ]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

Метод .info() выведет список всех колонок, посчитает, сколько в них непустых значений, и укажет, какого типа данные в них лежат. object - это обычно строка.

In [ ]:
titanic.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

Метод .describe() выведет для каждой из цифровых колонок таблички число непустых значений, их среднее арифметическое, [стандартное отклонение](https://ru.wikipedia.org/wiki/%D0%A1%D1%80%D0%B5%D0%B4%D0%BD%D0%B5%D0%BA%D0%B2%D0%B0%D0%B4%D1%80%D0%B0%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D0%BE%D1%82%D0%BA%D0%BB%D0%BE%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5), самое маленькое значение, [квантили](https://ru.wikipedia.org/wiki/%D0%9A%D0%B2%D0%B0%D0%BD%D1%82%D0%B8%D0%BB%D1%8C#%D0%9C%D0%B5%D0%B4%D0%B8%D0%B0%D0%BD%D0%B0_%D0%B8_%D0%BA%D0%B2%D0%B0%D1%80%D1%82%D0%B8%D0%BB%D0%B8) и максимальное значение.

(Все эти термины статистики подробно будете разбирать в след. семестре).

Таблички в pandas особенно хороши тем, что можно брать только какие-то их части, как в excel с фильтром, при этом сама библиотека очень экономит оперативную память; можно с помощью условий заставить pandas показать только те строчки, значения в которых удовлетворяют нашему условию. Например, хотим получить только тех пассажиров, которые выжили (Survived = 1) и при этом плыли третьим классом (Pclass):

In [ ]:
titanic[(titanic.Survived == 1) & (titanic.Pclass == 3)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
838,839,1,3,"Chip, Mr. Chang",male,32.0,0,0,1601,56.4958,NaN,S
855,856,1,3,"Aks, Mrs. Sam (Leah Rosen)",female,18.0,0,1,392091,9.3500,NaN,S
858,859,1,3,"Baclini, Mrs. Solomon (Latifa Qurban)",female,24.0,0,3,2666,19.2583,NaN,C
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.0,1,1,347742,11.1333,NaN,S
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C

Получим в результате такую же табличку, которую можно будет сохранить в отдельную переменную и работать с ней как хотим.

Обратите внимание, что условия соединяются как булевы маски в numpy!

В табличках могут быть пропущенные значения ячеек: когда в ячейке вообще ничего нет. Либо в числовых столбцах может быть NaN - эту константу pandas также унаследовал от numpy.

Можно проверить, есть ли в нашей таблице такие значения, если использовать следующую комбинацию:

In [ ]:
titanic.isna().any()

PassengerId    False
Survived       False
Pclass         False
Name           False
Sex            False
Age             True
SibSp          False
Parch          False
Ticket         False
Fare           False
Cabin           True
Embarked        True
dtype: bool

Метод isna() возвращает True, если есть пропуск, а any() возвращает True, если хотя бы одна ячейка при проверке isna() дала True. Видим, что не у всех указаны возраст, кабина и какое-то значение посадки.

Можно также посмотреть уникальные значения для любого столбца таблицы, двумя способами:

In [ ]:
print(set(titanic.Sex))
print(titanic['Sex'].unique())

{'male', 'female'}
['male' 'female']

Количество уникальных элементов можно посчитать с помощью len() и .unique(), а можно сразу, с помощью метода .nunique().

#### Агрегации

Агрегация - это важный способ получать новые данные при анализе. Как мы уже знаем из numpy, в результате агрегации можно получить одно значение, а можно набор значений по осям.

Когда мы говорим, что агрегируем данные по осям, это означает, что мы их по сути группируем. В pandas есть разные способы группировки данных. Самый простой - это использовать метод .groupby().

Но groupby позволяет сгруппировать данные только по какому-то одному столбцу (признаку). Обычно к результату метода применяется .mean() или .sum().

In [ ]:
titanic.groupby('Sex').mean()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
Sex,,,,,,,
female,461.818182,0.931818,1.215909,32.676136,0.534091,0.545455,89.000900
male,449.389474,0.431579,1.168421,38.451789,0.400000,0.410526,69.124343

Эти методы можно применять и к отдельному столбцу, и к таблице целиком. Но если в таблице есть не только числовые данные, лучше считать по столбцам с помощью groupby, а для таблицы целиком используйте тогда describe().

In [ ]:
titanic.Age.mean()

29.69911764705882

In [ ]:
titanic.Survived.sum()

342

Более хитрый способ группировки - использовать pivot_table(). Почитать о нем можно [здесь](https://www.kaggle.com/kamilpolak/tutorial-how-to-use-pivot-table-in-pandas). (Еще больше узнать про pivot_table(), а также про другие методы pandas, вам поможет простая и доступная документация, к которой я всячески призываю обращаться.)

In [ ]:
pd.pivot_table(df, index=['Manager', 'Rep'], values=['Price'], columns=['Product'], aggfunc=[np.sum, np.mean])

                                  sum                                  mean  \
                                Price                                 Price
Product                           CPU Maintenance Monitor Software      CPU
Manager       Rep
Debra Henley  Craig Booker    65000.0      5000.0     NaN  10000.0  32500.0
              Daniel Hilton  105000.0         NaN     NaN  10000.0  52500.0
              John Smith      35000.0      5000.0     NaN      NaN  35000.0
Fred Anderson Cedric Moss     95000.0      5000.0     NaN  10000.0  47500.0
              Wendy Yule     165000.0      7000.0  5000.0      NaN  82500.0



Product                     Maintenance Monitor Software
Manager       Rep
Debra Henley  Craig Booker       5000.0     NaN  10000.0
              Daniel Hilton         NaN     NaN  10000.0
              John Smith         5000.0     NaN      NaN
Fred Anderson Cedric Moss        5000.0     NaN  10000.0
              Wendy Yule         7000.0  5000.0      NaN

То есть, pivot_table позволяет группировать данные по нескольким признакам сразу, а еще отдельно считать несколько разных функций на сгруппированных значениях (можно одновременно узнать и среднее арифметическое, и сумму, и что захотите, в принципе).

#### Как можно изменять таблицы?

Во-первых, можно чистить табличку от пропусков. Это делается так:

In [ ]:
titanic.dropna() # такая чистка вернет новую таблицу, а старая останется неизменной

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

Или так:

In [ ]:
titanic.dropna(inplace=True)  # параметр inplace=True заставит pandas вносить изменения прямо в текущую табличку

Можно удалить и вообще любую произвольную строчку:

In [ ]:
titanic.drop(1) # c методом drop() то же самое: можно сохранять изменения в текущей табличке, а можно создавать новую.

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

Если хотим удалить целый столбец, нужно указать ось (строчки у нас - это как бы х на графике, а столбцы = это y)

In [ ]:
titanic.drop('SibSp', axis=1)

,PassengerId,Survived,Pclass,Name,Sex,Age,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,17463,51.8625,E46,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,695,5.0000,B51 B53 B55,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,111369,30.0000,C148,C

Если хотим удалить из таблички повторяющиеся строки, можно использовать:

In [ ]:
titanic.drop_duplicates(keep='first', inplace=True)  # я запускать не стала, потому что в Титанике нет повторяющихся строк.

Если хотим что-то добавить в табличку, для строк можно воспользоваться loc:

In [ ]:
df3

   col1  col2
0     1     4
1     2     5
2     3     6

In [ ]:
df3.loc[3] = [7, 8]
df3

   col1  col2
0     1     4
1     2     5
2     3     6
3     7     8

Обратите внимание, iloc здесь пользоваться нельзя - он умеет только перезаписывать уже существующие строки.

Можно добавить и столбец:

In [ ]:
df3['col3'] = pd.Series(['x', 'y', 'z', 'w'])
df3

   col1  col2 col3
0     1     4    x
1     2     5    y
2     3     6    z

Можно добавлять столбцы на основе уже существующих, а также изменять существующие с помощью какой-то функции, которая будет применяться к каждой ячейке столбца, с помощью метода .apply().

In [ ]:
df3['col1'].apply(lambda x: x + 1)  # увеличим все числа в столбце 1 на 1

0    2
1    3
2    4
Name: col1, dtype: int64

In [ ]:
df3['col4'] = df3.col3.apply(len)
df3

   col1  col2 col3  col4
0     1     4    x     1
1     2     5    y     1
2     3     6    z     1

Можно использовать .apply() и со всей таблицей:

In [ ]:
df3.apply(lambda x: x * 2)

   col1  col2 col3
0     2     8   xx
1     4    10   yy
2     6    12   zz
3    14    16   ww

Также в pandas есть готовый метод OHE (One Hot Encoding), про который можно почитать на [вики](https://en.wikipedia.org/wiki/One-hot). Он полезен, если у нас есть колонка с категориальным признаком. Что такое категориальный признак? Даже если он из чисел, в отличие от цифрового, эти числа между собой арифметически не соотносятся. Чаще, впрочем, категориальный признак - это что-то вроде "из какого города": у нас есть n городов, и мы не можем их просто пронумеровать, потому что если мы укажем, что Москва у нас - 1, а Петербург - 2, то разве Петербург больше Москвы? Что это будет значить? В этом случае можно применить OHE в pandas к ней и получить дополнительные колонки:

In [ ]:
new_cols = pd.get_dummies(df.column_name, prefix='prefix', drop_first=True)

В Титанике нет удобных столбцов с признаками, которые хотелось бы заменить, поэтому код абстрактный. То есть, в строке выше мы создаем дополнительную табличку из n - 1 колонок для n вариантов значений колонки column_name с префиксом (названия колонок будут prefix_1, prefix_2...), и удаляем сразу первый столбец, потому что он избыточный для OHE.

Дальше можно смержить получившееся:

    df.drop('column_name', inplace=True) # исходный столбец больше не нужен
    df = df.join(new_cols)